<html>

<head>
</head>

<body>
<form action='/test/select' method="post">

    <button  name="test" value="111" >nihao</button>
    <button  name="test" value="122" >nihao</button>
    <button  name="test" value="133" >nihao</button>


    <table class="table">
        <form action='/test/select' method="post" id="fm">
            <tr><td colspan="2" bgcolor="#6495ed" ><font color="white" face="楷体"><b>添加用户</b></font></td></tr>
            <tr><td>用户名称</td><td><input type="text" name="name" ></td></tr>
            <tr><td>用户密码</td><td><input type="text" name="psw"></td></tr>
            <tr><td><input type="submit" value="确定"><td><button class="cancel">取消</button></td></tr>
        </form>
    </table>





</body>

</html>

