<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <!--按钮跳转页面-->
    <script language="javascript" type="">
        function countDown(secs){
            tiao.innerText=secs;
            if(--secs>0)
                setTimeout("countDown("+secs+")",1000);
        }
        countDown(3);
    </script>
    <!--脚本结束-->
</head>
<body>


<table border="10" align="center">
    <tr><td colspan="8" align="center" ><h1>开台</h1></td></tr>
    <tr>
        <td>桌号</td><td><select>
                <option value="1">我是下拉项目1</option>
                <option value="2">我是下拉项目2</option>
                <option value="3">我是下拉项目3</option>
                <option value="4">我是下拉项目4</option></select></td>
        <td>就餐人数</td><td><input type="text" name="order_number"></td>
        <td>服务员</td><td><input type="text" name="order_waiter"></td>
        <?php  echo"<td>就餐日期</td><td>".date("Y年m月d日")."</td>"; ?>
    </tr>
</table>



    <table align="center">
        <tr><td><input type="button"  name="yse" value="确定" >

        <input name="select" type="button" value="订单搜索" onClick="location.href='../backstage/selectorder'">
            </td></tr>
        <tr><td><input name="orderdishes" type="button" value="点菜" onClick="location.href='../dishes/dishes'"></td></tr>
        <tr><td><input name="checkout" type="button" value="买单" onClick="location.href='../accounts/accounts'"></td></tr>
    </table>


    </center>
</body>
</html>