<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

</head>
<body>
<h1>餐厅管理系统</h1>
<table>
    <form action='/login/login' method="post" id="fm">
        <tr><td>用户名称</td><td><input type="text" name="user_name" ></td></tr>
        <tr><td>密&nbsp&nbsp码</td><td><input type="text" name="password"></td></tr>
        <tr><td><input type="submit" value="登陆"></td><td><input type="reset" value="重置"></td></tr>
    </form>
</table>

</body>
</html>


