<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title>高考信息查询系统</title><!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>index</title>
	<link rel="stylesheet" type="text/css" href="/jquery-easyui-1.3.6/themes/default/easyui.css" />
	<link rel="stylesheet" type="text/css" href="/jquery-easyui-1.3.6/themes/icon.css" />
	<script type="text/javascript" src="/jquery-easyui-1.3.6/jquery.min.js"></script>
	<script type="text/javascript" src="/jquery-easyui-1.3.6/jquery.easyui.min.js"></script>
	<script type="text/javascript" src="/jquery-easyui-1.3.6/locale/easyui-lang-zh_CN.js"></script>
<style type="text/css">
		#fm{
			margin:0;
			padding:10px 30px;
		}
		.ftitle{
			font-size:14px;
			font-weight:bold;
			color:#666;
			padding:5px 0;
			margin-bottom:10px;
			border-bottom:1px solid #ccc;
		}
		.fitem{
			margin-bottom:5px;
		}
		.fitem label{
			display:inline-block;
			width:80px;
		}
	</style>
	<script type="text/javascript">
	
		
	

		
	var url;
	function newPro(){
		$('#dlg').dialog('open').dialog('setTitle','新学校');
		$('#fm').form('clear');
		url = "/manage/addschool";
	}
	function editPro(){
		var row = $('#dg').datagrid('getSelected');
		if (row){
			$('#dlg').dialog('open').dialog('setTitle','编辑学校');
			$('#fm').form('load',row);
			url = '/manage/updateschool?id='+row.user_id;
		}
	}
	function savePro(){
		$('#fm').form('submit',{
			url: url,
			onSubmit: function(){
				return $(this).form('validate');
			},
			success: function(result){
				var result = eval('('+result+')');
				if (result.success){
					$('#dlg').dialog('close');		// close the dialog
					$('#dg').datagrid('reload');	// reload the user data
				} else {
					$.messager.show({
						title: 'Error',
						msg: result.msg
					});
				}
			}
		});
	}
	function removeUser(){
		var row = $('#dg').datagrid('getSelected');
		if (row){
			$.messager.confirm('警告','确定要删除？',function(r){
				if (r){
					$.post('/manage/delschool',{school_id:row.school_id},function(result){
						if (result.success){
							$('#dg').datagrid('reload');	// reload the user data
						} else {
							$.messager.show({	// show error message
								title: '错误',
								msg: result.msg
							});
						}
					},'json');
				}
			});
		}
	}

</script>

</head>
<body >

<!-- 整体表格 -->

	<table id="dg" title="学校信息表" class="easyui-datagrid"
			url="/manage/schoolserve" fit="true" 
			toolbar="#toolbar" pagination="true"
			rownumbers="true" fitColumns="true" singleSelect="true"
			loadMsg="数据加载中..." >
		<thead>
			<tr>
				<th field="school_id" width="25">学校编号</th>
				<th field="school_name" width="45">学校名称</th>
				<th field="found_date" width="45">创立时间</th>
				<th field="school_web" width="50">官网</th>
				<th field="post_code" width="30">邮编</th>
				<th field="school_address" width="65">地址</th>
				<th field="office_phone" width="45">电话</th>
				<th field="school_type" width="45">类别</th>
			</tr>
		</thead>
	</table>
	
	
<!-- 按钮 -->
	<div id="toolbar">
		<a class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="newPro()">添加学校</a>
		<a class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="editPro()">编辑学校</a>
		<a class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="removeUser()">删除学校</a>
	</div>
	
	
<!-- 增加学校 -->	
	<div id="dlg" class = "easyui-dialog" closed = "true" title = "新学校" style ="width:400px;height:500px;">   
	<h2>学校信息</h2>
	<hr />
				<form id="fm" method="post">
                	<br/>    
                	<div>   
                		<label for="name">学校编号：</label>   
                        <input style="width:200px;bgcolor:gray;" class="easyui-validatebox" type="text" name="school_id"  data-options="required:true"
                        		missingMessage="请输入学校编号"/>   
                    </div>   
                    <div>   
                        <label for="name">学校名称：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="school_name" data-options="required:true"
                        		missingMessage="请输入学校名称" />   
                    </div>   
                    <div>   
                        <label for="password">创立时间：</label>   
                        <input style="width:200px" class="easyui-datebox" type="text" id="dd" name="found_date" data-options="required:true"
                       			missingMessage="请输入创立时间" />   
                    </div> 
                    <div>   
                        <label for="password">学校官网：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="school_web" data-options="required:true" 
                        		missingMessage="请输入学校官网" /> 
                    </div> 
                    <div>   
                        <label for="password">学校邮编：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="post_code" data-options="required:true" 
                        		missingMessage="请输入学校邮编" /> 
                    </div> 
                    <div>   
                        <label for="password">学校地址：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="school_address" data-options="required:true"
                       			missingMessage="请输入学校地址" />   
                    </div> 
                    <div>   
                        <label for="password">学校电话：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="office_phone" data-options="required:true"
                       			missingMessage="请输入学校电话" />   
                    </div> 
                    <div>   
                        <label for="password">经&nbsp;&nbsp;&nbsp;&nbsp;度：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="longitude" data-options="required:true"
                       			missingMessage="请输入经度" />   
                    </div> 
                     <div>   
                        <label for="password">纬&nbsp;&nbsp;&nbsp;&nbsp;度：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="latitude" data-options="required:true"
                       			missingMessage="请输入纬度" />   
                    </div> 
                    <div>   
                        <label for="password">学校类别：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="school_type" data-options="required:true"
                       			missingMessage="请输入类别" />   
                    </div> 
                    <div>   
                        <label for="password">男女比例：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="sex_ratio" data-options="required:true"
                       			missingMessage="请输入男女比例" />   
                    </div> 
                    <div>   
                        <label for="password">学校排行：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="rank" />   
                    </div> 
                    <div>   
                        <label for="password">环境指数：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="environment"/>   
                    </div> 
                    <div>   
                        <label for="password">学校简介：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="introduction" data-options="required:true"
                       			missingMessage="请输入学校简介" />   
                    </div> 
                   
                    <div id="dlg-buttons" style="text-align: center;margin-top:20px;">
<a href="#" class="easyui-linkbutton" iconCls="icon-ok" onClick="savePro()">保存</a>
<a href="#" class="easyui-linkbutton" iconCls="icon-cancel" onClick="javascript:$('#dlg').dialog('close')">取消</a>
					</div>
                </form>  
	</div>   

</body>
</html>	