<!DOCTYPE html>
<html>
<head>
	<meta charset="UTF-8">
	<title>index</title>
	<link rel="stylesheet" type="text/css" href="/jquery-easyui-1.3.6/themes/default/easyui.css" />
	<link rel="stylesheet" type="text/css" href="/jquery-easyui-1.3.6/themes/icon.css" />
	<script type="text/javascript" src="/jquery-easyui-1.3.6/jquery.min.js"></script>
	<script type="text/javascript" src="/jquery-easyui-1.3.6/jquery.easyui.min.js"></script>
	<script type="text/javascript" src="/jquery-easyui-1.3.6/locale/easyui-lang-zh_CN.js"></script>
<style type="text/css">
		#fm{
			margin:0;
			padding:10px 30px;
		}
		.ftitle{
			font-size:14px;
			font-weight:bold;
			color:#666;
			padding:5px 0;
			margin-bottom:10px;
			border-bottom:1px solid #ccc;
		}
		.fitem{
			margin-bottom:5px;
		}
		.fitem label{
			display:inline-block;
			width:80px;
		}
	</style>
	<script type="text/javascript">
	var url;
	function newPro(){
		$('#dlg').dialog('open').dialog('setTitle','新用户');
		$('#fm').form('clear');
		url = "/manage/adduser";
	}
	function editPro(){
		var row = $('#dg').datagrid('getSelected');
		if (row){
			$('#dlg').dialog('open').dialog('setTitle','编辑用户');
			$('#fm').form('load',row);
			url = '/manage/updateuser?id='+row.user_id;
		}
	}
	function savePro(){
		$('#fm').form('submit',{
			url: url,
			onSubmit: function(){
				return $(this).form('validate');
			},
			success: function(result){
				var result = eval('('+result+')');
				if (result.success){
					$('#dlg').dialog('close');		// close the dialog
					$('#dg').datagrid('reload');	// reload the user data
				} else {
					$.messager.show({
						title: 'Error',
						msg: result.msg
					});
				}
			}
		});
	}
	function removeUser(){
		var row = $('#dg').datagrid('getSelected');
		if (row){
			$.messager.confirm('警告','确定要删除？',function(r){
				if (r){
					$.post('/manage/deluser',{user_id:row.user_id},function(result){
						if (result.success){
							$('#dg').datagrid('reload');	// reload the user data
						} else {
							$.messager.show({	// show error message
								title: '错误',
								msg: result.msg
							});
						}
					},'json');
				}
			});
		}
	}

</script>

</head>
<body >

<!-- 整体表格 -->

	<table id="dg" title="用户信息表" class="easyui-datagrid"
			url="/manage/userlistserve" fit="true" 
			toolbar="#toolbar" pagination="true"
			rownumbers="true" fitColumns="true" singleSelect="true"
			loadMsg="数据加载中..." >
		<thead>
			<tr>
				<th field="user_id" width="45">用户 id</th>
				<th field="username" width="45">用户姓名</th>
				<th field="nickname" width="45">昵称</th>
				<th field="sex" width="10">性别</th>
				<th field="email" width="45">邮箱</th>
				<th field="tel" width="45">电话</th>
				<th field="qq" width="45">QQ</th>
				<th field="registertime" width="45">注册时间</th>
				<th field="is_manager" width="45">是否管理员</th>
			</tr>
		</thead>
	</table>
	
	
<!-- 按钮 -->
	<div id="toolbar">
		<a class="easyui-linkbutton" iconCls="icon-add" plain="true" onclick="newPro()">添加用户</a>
		<a class="easyui-linkbutton" iconCls="icon-edit" plain="true" onclick="editPro()">编辑用户</a>
		<a class="easyui-linkbutton" iconCls="icon-remove" plain="true" onclick="removeUser()">删除用户</a>
	</div>
	
	
<!-- 增加用户 -->	
	<div id="dlg" class = "easyui-dialog" closed = "true" title = "新用户" style ="width:400px;height:400px;">   
	<h2>用户信息</h2>
	<hr />
				<form id="fm" method="post">
                	<br/>    
                	<div>   
                        <input style="width:200px;bgcolor:gray;" class="easyui-validatebox" type="hidden" name="user_id" onfocus="this.blur()"
                        		/>   
                    </div>   
                    <div>   
                        <label for="name">用户姓名：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="username" data-options="required:true"
                        		missingMessage="请输入用户姓名" />   
                    </div>   
                    <div>   
                        <label for="password">昵&nbsp;&nbsp;&nbsp;&nbsp;称：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="nickname" data-options="required:true"
                       			missingMessage="请输入用户昵称" />   
                    </div> 
                    <div>   
                        <label for="password">密&nbsp;&nbsp;&nbsp;&nbsp;码：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="password" name="password1" data-options="required:true" 
                        		missingMessage="请输入用户密码" /> 
                    </div> 
                    <div>   
                        <label for="password">性&nbsp;&nbsp;&nbsp;&nbsp;别：</label>   
                        <input type="radio" name="sex"  value="男" />男
						<input type="radio" name="sex" value="女" />女 <br/>
                    </div> 
                    <div>   
                        <label for="password">邮&nbsp;&nbsp;&nbsp;&nbsp;箱：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="email" data-options="required:true"
                       			missingMessage="请输入用户Email" />   
                    </div> 
                    <div>   
                        <label for="password">电&nbsp;&nbsp;&nbsp;&nbsp;话：</label>   
                        <input style="width:200px" class="easyui-validatebox" type="text" name="tel" data-options="required:true"
                       			missingMessage="请输入用户Tel" />   
                    </div> 
                    <div>   
                        <label for="password">信&nbsp;&nbsp;&nbsp;&nbsp;息：</label>   
                        <input style="width:200px" type="text" name="info"/>   
                    </div> 
                    <div>   
                        <label for="is_manager">是否管理员：</label>   
                        <input type="radio" name="is_manager"  value="1" />是
						<input type="radio" name="is_manager" value="0" />否 <br/>
                    </div> 
                    <div id="dlg-buttons" style="text-align: center;margin-top:20px;">
<a href="#" class="easyui-linkbutton" iconCls="icon-ok" onClick="savePro()">保存</a>
<a href="#" class="easyui-linkbutton" iconCls="icon-cancel" onClick="javascript:$('#dlg').dialog('close')">取消</a>
					</div>
                </form>  
	</div>   

</body>
</html>	