<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href="/css/default.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" type="text/css" href="/js/themes/default/easyui.css" />
    <link rel="stylesheet" type="text/css" href="/js/themes/icon.css" />
    <script type="text/javascript" src="/js/jquery-1.4.2.min.js"></script>
    <script type="text/javascript" src="/js/jquery.easyui.js"></script>
	<script type="text/javascript" src='/js/outlook2.js'> </script>
	<script type="text/javascript" src="/jquery-easyui-1.3.6/locale/easyui-lang-zh_CN.js"></script>
	<title>高考信息查询系统</title>
	
	</head>
		<body style="padding: 50px;">
		<form action="/feedback/advice" method="post">
		发表昵称：
		<input type="text" name="advicer" onfocus=this.blur() value="<?=$this->nickname?>"/><br/>
		发表时间：
		<input type="text" name="time" onfocus=this.blur() value="<?php echo date('Y-m-d')?>"/><br/>
		意见内容：<br/>
		<div style="margin-left:65px;float:left">
			<textarea style="width:400px;height:250px;resize: none;" name="content"></textarea><br/>
			<input type="submit" value="提交"/>
			<input type="reset" value="重置"/>
		</div>
		<div style="float: right"><img src="/images/advice.png"></div>
		</form>
		</body>
			
</html>